# Generated by Django 5.2.17 on 2026-09-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='status',
        ),
    ]
