# Generated by Django 5.2.17 on 2026-09-18 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_initial'),
        ('exam', '0003_remove_job_num_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'question_labels',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='questiongenerationjob',
            name='question_types',
            field=models.JSONField(help_text='Counts per type, e.g. {"mcq": 2, "short": 3}'),
        ),
        migrations.AddField(
            model_name='question',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='questions', to='exam.label'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['grade', 'subject'], name='idx_question_grade_subject'),
        ),
    ]
