# Generated by Django 5.2.17 on 2026-09-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_question_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='total_marks',
        ),
    ]
