# Generated by Django 5.2.17 on 2026-09-18 12:54

from django.db import migrations, models
from django.db.models import Count, Sum


def backfill_exam_totals(apps, schema_editor):
    Exam = apps.get_model('exam', 'Exam')
    for exam in Exam.objects.all().iterator():
        aggregates = exam.exam_questions.aggregate(
            marks=Sum('marks'),
            count=Count('id'),
        )
        Exam.objects.filter(pk=exam.pk).update(
            total_marks=aggregates['marks'] or 0,
            question_count=aggregates['count'] or 0,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_exam_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='question_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_marks',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(backfill_exam_totals, migrations.RunPython.noop),
    ]
